kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kisansahayak
nodes:
  - role: control-plane
    extraPortMappings:
      # App accessible at http://server-ip:30500
      - containerPort: 30500
        hostPort: 30500
        protocol: TCP
      # PostgreSQL accessible from host (debugging only)
      - containerPort: 30432
        hostPort: 30432
        protocol: TCP
